export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCESS = 'ADD_PRODUCT_SUCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_GET_PRODUCTS = 'START_GET_PRODUCTS';
export const GET_PRODUCTS_SUCCSESS = 'GET_PRODUCTS_SUCCSESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_REMOVE_PRODUCT = 'GET_REMOVE_PRODUCT';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_ERROR = 'REMOVE_PRODUCT_ERROR';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const EDIT_PRODUCT_SUCESS = 'EDIT_PRODUCT_SUCESS';
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';